/*
 *****************************************************************************
 *                                                                           *
 *                 IMPINJ CONFIDENTIAL AND PROPRIETARY                       *
 *                                                                           *
 * This source code is the sole property of Impinj, Inc.  Reproduction or    *
 * utilization of this source code in whole or in part is forbidden without  *
 * the prior written consent of Impinj, Inc.                                 *
 *                                                                           *
 * (c) Copyright Impinj, Inc. 2010. All rights reserved.                     *
 *                                                                           *
 *****************************************************************************
 */

/*
 *****************************************************************************
 *
 * $Id: hostifregs.h,v 1.103 2011/03/24 20:15:21 dshaheen Exp $
 * 
 * Description:
 *
 *   This file is automatically generated.
 *   Automatic Generator File: source_macregister.pl (Version 1.14)
 *   Reference File: mac_registers.xml (Version 1.232)
 *
 *****************************************************************************
 */

#ifndef H_HOSTIFREGS_H
#define H_HOSTIFREGS_H

/* Register Name / Address Constants */

#define MAC_VER                                  0x0000
#define MAC_INFO                                 0x0001
#define MAC_RFTRANSINFO                          0x0002
#define MAC_DBG1                                 0x0003
#define MAC_DBG2                                 0x0004
#define MAC_ERROR                                0x0005
#define MAC_LAST_ERROR                           0x0006
#define MAC_STATE                                0x0007
#define MAC_XCVR_HEALTH_CHECK_FAIL_COUNT         0x0008
#define MAC_LAST_COMMAND_DURATION                0x0009
#define MAC_KEY                                  0x000A
#define MAC_ERROR_DIAGNOSTIC_SEL                 0x000B
#define MAC_ERROR_DIAGNOSTIC                     0x000C
#define MAC_FW_DEFAULT_VALUE_SOURCE              0x000D
#define MAC_NV_UPDATE_CONTROL                    0x000E
#define MAC_BL_VER                               0x000F
#define MAC_ACTIVE_FW                            0x0010
#define MAC_FW_CRC                               0x0011
#define MAC_MICROPROCESSOR_ID                    0x0012
#define HST_ENGTEST_ARG0                         0x0100
#define HST_ENGTEST_ARG1                         0x0101
#define HST_DBG1                                 0x0102
#define RESERVED_0x0103                          0x0103
#define HST_TX_RANDOM_DATA_DURATION              0x0104
#define HST_TX_RANDOM_DATA_CONTROL               0x0105
#define HST_TX_RANDOM_DATA_ON_TIME               0x0106
#define HST_TX_RANDOM_DATA_OFF_TIME              0x0107
#define HST_SET_FREQUENCY_CFG                    0x0108
#define HST_SET_FREQUENCY_CHANNEL                0x0109
#define HST_SET_FREQUENCY_KHZ                    0x010A
#define HST_SET_FREQUENCY_PLLDIVMULT             0x010B
#define HST_SET_FREQUENCY_PLLDACCTL              0x010C
#define HST_TEST_FREQUENCY_PLLDIVMULT            0x010D
#define HST_TEST_FREQUENCY_PLLDACCTL             0x010E
#define RESERVED_0x010F                          0x010F
#define HST_TEST_INVENTORY_CFG                   0x0110
#define HST_ENGTEST_RESULT_SEL                   0x0111
#define HST_ENGTEST_RESULT                       0x0112
#define HST_TEST_ANTENNA                         0x0113
#define HST_TEST_RFPOWER                         0x0114
#define HST_INJECT_RANDOM_TX_COUNT               0x0115
#define HST_TEST_MANUAL_OVERRIDE                 0x0116
#define RESERVED_0x0117                          0x0117
#define RESERVED_0x0118                          0x0118
#define RESERVED_0x0119                          0x0119
#define RESERVED_0x011A                          0x011A
#define RESERVED_0x011B                          0x011B
#define RESERVED_0x011C                          0x011C
#define RESERVED_0x011D                          0x011D
#define RESERVED_0x011E                          0x011E
#define RESERVED_0x011F                          0x011F
#define HST_FORMAT_OEM_CONFIGURATION             0x0120
#define HST_FORMAT_OEM_KEY_CHECK                 0x0121
#define RESERVED_0x0122                          0x0122
#define HST_CALIBRATION_CONTROL                  0x0123
#define HST_CAL_PA_BIAS_CONFIG                   0x0124
#define HST_CAL_PA_BIAS_MEASUREMENT              0x0125
#define HST_CAL_PA_BIAS_TARGET_CURRENT           0x0126
#define HST_CAL_PA_BIAS_CURRENT_PER_LSB          0x0127
#define HST_CAL_GROSSGAIN_CONFIG                 0x0128
#define HST_PWRMGMT                              0x0200
#define HST_CMNDIAGS                             0x0201
#define HST_TRACE                                0x0202
#define HST_IMPINJ_EXTENSIONS                    0x0203
#define HST_PWRMGMT_STATUS                       0x0204
#define HST_REGULATORY_REGION                    0x0300
#define HST_PROTSCH_LBTCFG                       0x0301
#define RESERVED_0x0302                          0x0302
#define HST_PROTSCH_FTIME                        0x0303
#define RESERVED_0x0304                          0x0304
#define RESERVED_0x0305                          0x0305
#define HST_PROTSCH_TXTIME_ON                    0x0306
#define HST_PROTSCH_TXTIME_OFF                   0x0307
#define RESERVED_0x0308                          0x0308
#define RESERVED_0x0309                          0x0309
#define HST_PROTSCH_ADJCW                        0x030A
#define RESERVED_0x030B                          0x030B
#define HST_PROTSCH_TXTIME_ON_OVHD               0x030C
#define HST_PROTSCH_TXTIME_OFF_OVHD              0x030D
#define HST_PROTSCH_LBTRSSI                      0x030E
#define HST_MBP_ADDR                             0x0400
#define HST_MBP_DATA                             0x0401
#define RESERVED_0x0402                          0x0402
#define RESERVED_0x0403                          0x0403
#define RESERVED_0x0404                          0x0404
#define RESERVED_0x0405                          0x0405
#define RESERVED_0x0406                          0x0406
#define RESERVED_0x0407                          0x0407
#define HST_LPROF_SEL                            0x0408
#define HST_LPROF_ADDR                           0x0409
#define HST_LPROF_DATA                           0x040A
#define HST_OEM_ADDR                             0x0500
#define HST_OEM_DATA                             0x0501
#define HST_OEM_STRING_TYPE                      0x0502
#define HST_OEM_STRING_LENGTH                    0x0503
#define HST_OEM_STRING_CHAR_SEL                  0x0504
#define HST_OEM_STRING_CHAR                      0x0505
#define HST_GPIO_INMSK                           0x0600
#define HST_GPIO_OUTMSK                          0x0601
#define HST_GPIO_OUTVAL                          0x0602
#define HST_GPIO_CFG                             0x0603
#define HST_ANT_CYCLES                           0x0700
#define HST_ANT_DESC_SEL                         0x0701
#define HST_ANT_DESC_CFG                         0x0702
#define MAC_ANT_DESC_STAT                        0x0703
#define HST_ANT_DESC_PORTDEF                     0x0704
#define HST_ANT_DESC_DWELL                       0x0705
#define HST_ANT_DESC_RFPOWER                     0x0706
#define HST_ANT_DESC_INV_CNT                     0x0707
#define HST_TAGMSK_DESC_SEL                      0x0800
#define HST_TAGMSK_DESC_CFG                      0x0801
#define HST_TAGMSK_BANK                          0x0802
#define HST_TAGMSK_PTR                           0x0803
#define HST_TAGMSK_LEN                           0x0804
#define HST_TAGMSK_0_3                           0x0805
#define HST_TAGMSK_4_7                           0x0806
#define HST_TAGMSK_8_11                          0x0807
#define HST_TAGMSK_12_15                         0x0808
#define HST_TAGMSK_16_19                         0x0809
#define HST_TAGMSK_20_23                         0x080A
#define HST_TAGMSK_24_27                         0x080B
#define HST_TAGMSK_28_31                         0x080C
#define HST_QUERY_CFG                            0x0900
#define HST_INV_CFG                              0x0901
#define HST_INV_SEL                              0x0902
#define HST_INV_ALG_PARM_0                       0x0903
#define HST_INV_ALG_PARM_1                       0x0904
#define HST_INV_ALG_PARM_2                       0x0905
#define HST_INV_ALG_PARM_3                       0x0906
#define HST_INV_RSSI_FILTERING_CONFIG            0x0907
#define HST_INV_RSSI_FILTERING_THRESHOLD         0x0908
#define HST_INV_RSSI_FILTERING_COUNT             0x0909
#define RESERVED_0x090A                          0x090A
#define RESERVED_0x090B                          0x090B
#define RESERVED_0x090C                          0x090C
#define RESERVED_0x090D                          0x090D
#define RESERVED_0x090E                          0x090E
#define RESERVED_0x090F                          0x090F
#define RESERVED_0x0910                          0x0910
#define HST_INV_EPC_MATCH_CFG                    0x0911
#define HST_INV_EPCDAT_0_3                       0x0912
#define HST_INV_EPCDAT_4_7                       0x0913
#define HST_INV_EPCDAT_8_11                      0x0914
#define HST_INV_EPCDAT_12_15                     0x0915
#define HST_INV_EPCDAT_16_19                     0x0916
#define HST_INV_EPCDAT_20_23                     0x0917
#define HST_INV_EPCDAT_24_27                     0x0918
#define HST_INV_EPCDAT_28_31                     0x0919
#define HST_INV_EPCDAT_32_35                     0x091A
#define HST_INV_EPCDAT_36_39                     0x091B
#define HST_INV_EPCDAT_40_43                     0x091C
#define HST_INV_EPCDAT_44_47                     0x091D
#define HST_INV_EPCDAT_48_51                     0x091E
#define HST_INV_EPCDAT_52_55                     0x091F
#define HST_INV_EPCDAT_56_59                     0x0920
#define HST_INV_EPCDAT_60_63                     0x0921
#define RESERVED_0x0922                          0x0922
#define RESERVED_0x0923                          0x0923
#define RESERVED_0x0924                          0x0924
#define RESERVED_0x0925                          0x0925
#define RESERVED_0x0926                          0x0926
#define RESERVED_0x0927                          0x0927
#define RESERVED_0x0928                          0x0928
#define RESERVED_0x0929                          0x0929
#define RESERVED_0x092A                          0x092A
#define RESERVED_0x092B                          0x092B
#define RESERVED_0x092C                          0x092C
#define RESERVED_0x092D                          0x092D
#define RESERVED_0x092E                          0x092E
#define RESERVED_0x092F                          0x092F
#define HST_INV_STATS_DURATION                   0x0930
#define HST_INV_STATS_QUERY                      0x0931
#define HST_INV_STATS_RN16RCV                    0x0932
#define HST_INV_STATS_RN16TO                     0x0933
#define HST_INV_STATS_EPCTO                      0x0934
#define HST_INV_STATS_TAGREADS                   0x0935
#define HST_INV_STATS_EPCCRC                     0x0936
#define HST_LBT_STATS_INTF_DURATION              0x0937
#define HST_LBT_STATS_INTF_COUNT                 0x0938
#define RESERVED_0x0A00                          0x0A00
#define HST_TAGACC_DESC_CFG                      0x0A01
#define HST_TAGACC_BANK                          0x0A02
#define HST_TAGACC_PTR                           0x0A03
#define HST_TAGACC_CNT                           0x0A04
#define HST_TAGACC_LOCKCFG                       0x0A05
#define HST_TAGACC_ACCPWD                        0x0A06
#define HST_TAGACC_KILLPWD                       0x0A07
#define HST_TAGWRDAT_SEL                         0x0A08
#define HST_TAGWRDAT_0                           0x0A09
#define HST_TAGWRDAT_1                           0x0A0A
#define HST_TAGWRDAT_2                           0x0A0B
#define HST_TAGWRDAT_3                           0x0A0C
#define HST_TAGWRDAT_4                           0x0A0D
#define HST_TAGWRDAT_5                           0x0A0E
#define HST_TAGWRDAT_6                           0x0A0F
#define HST_TAGWRDAT_7                           0x0A10
#define HST_TAGWRDAT_8                           0x0A11
#define HST_TAGWRDAT_9                           0x0A12
#define HST_TAGWRDAT_10                          0x0A13
#define HST_TAGWRDAT_11                          0x0A14
#define HST_TAGWRDAT_12                          0x0A15
#define HST_TAGWRDAT_13                          0x0A16
#define HST_TAGWRDAT_14                          0x0A17
#define HST_TAGWRDAT_15                          0x0A18
#define HST_TAGQTDAT                             0x0A19
#define MAC_RFTC_PAPWRLEV                        0x0B00
#define HST_RFTC_PAPWRCTL_PGAIN                  0x0B01
#define HST_RFTC_PAPWRCTL_IGAIN                  0x0B02
#define RESERVED_0x0B03                          0x0B03
#define MAC_RFTC_REVPWRLEV                       0x0B04
#define HST_RFTC_REVPWRTHRSH                     0x0B05
#define MAC_RFTC_AMBIENTTEMP                     0x0B06
#define HST_RFTC_AMBIENTTEMPTHRSH                0x0B07
#define MAC_RFTC_XCVRTEMP                        0x0B08
#define HST_RFTC_XCVRTEMPTHRESH                  0x0B09
#define MAC_RFTC_PATEMP                          0x0B0A
#define HST_RFTC_PATEMPTHRSH                     0x0B0B
#define RESERVED_0x0B0C                          0x0B0C
#define HST_RFTC_PAPWRCTL_AIWDELAY               0x0B0D
#define MAC_RFTC_PAPWRCTL_STAT0                  0x0B0E
#define MAC_RFTC_PAPWRCTL_STAT1                  0x0B0F
#define MAC_RFTC_PAPWRCTL_STAT2                  0x0B10
#define MAC_RFTC_PAPWRCTL_STAT3                  0x0B11
#define HST_RFTC_ANTSENSRESTHRSH                 0x0B12
#define HST_RFTC_IFLNAAGCRANGE                   0x0B13
#define MAC_RFTC_LAST_ANARXGAINNORM              0x0B14
#define HST_RFTC_OPENLOOPPWRCTRL                 0x0B15
#define HST_RFTC_SJC_CFG                         0x0B16
#define RESERVED_0x0B17                          0x0B17
#define RESERVED_0x0B18                          0x0B18
#define RESERVED_0x0B19                          0x0B19
#define HST_RFTC_DC_OFFSET_COEFF                 0x0B1A
#define HST_RFTC_CAL_PA_BIAS_DAC                 0x0B1B
#define HST_RFTC_GROSSGAIN_CONFIG                0x0B1C
#define HST_RFTC_CAL_GROSSGAIN_SEL               0x0B1D
#define HST_RFTC_CAL_GROSSGAIN_VALUE             0x0B1E
#define RESERVED_0x0B1F                          0x0B1F
#define HST_RFTC_CAL_GGNEG7_X                    0x0B20
#define HST_RFTC_CAL_GGNEG5_X                    0x0B21
#define HST_RFTC_CAL_GGNEG3_X                    0x0B22
#define HST_RFTC_CAL_GGNEG1_X                    0x0B23
#define HST_RFTC_CAL_GGPLUS1_X                   0x0B24
#define HST_RFTC_CAL_GGPLUS3_X                   0x0B25
#define HST_RFTC_CAL_GGPLUS5_X                   0x0B26
#define HST_RFTC_CAL_GGPLUS7_X                   0x0B27
#define RESERVED_0x0B28                          0x0B28
#define HST_RFTC_CAL_RFFWDPWR_A2                 0x0B29
#define HST_RFTC_CAL_RFFWDPWR_A1                 0x0B2A
#define HST_RFTC_CAL_RFFWDPWR_A0                 0x0B2B
#define HST_RFTC_FWDPWRTHRSH                     0x0B2C
#define RESERVED_0x0B2D                          0x0B2D
#define RESERVED_0x0B2E                          0x0B2E
#define RESERVED_0x0B2F                          0x0B2F
#define HST_RFTC_CLKDBLR_CFG                     0x0B30
#define HST_RFTC_CLKDBLR_SEL                     0x0B31
#define HST_RFTC_CLKDBLR_LUTENTRY                0x0B32
#define RESERVED_0x0B33                          0x0B33
#define RESERVED_0x0B34                          0x0B34
#define RESERVED_0x0B35                          0x0B35
#define RESERVED_0x0B36                          0x0B36
#define RESERVED_0x0B37                          0x0B37
#define RESERVED_0x0B38                          0x0B38
#define RESERVED_0x0B39                          0x0B39
#define RESERVED_0x0B3A                          0x0B3A
#define RESERVED_0x0B3B                          0x0B3B
#define RESERVED_0x0B3C                          0x0B3C
#define RESERVED_0x0B3D                          0x0B3D
#define RESERVED_0x0B3E                          0x0B3E
#define RESERVED_0x0B3F                          0x0B3F
#define HST_RFTC_FRQHOPMODE                      0x0B40
#define HST_RFTC_FRQHOPENTRYCNT                  0x0B41
#define HST_RFTC_FRQHOPTABLEINDEX                0x0B42
#define MAC_RFTC_HOPCNT                          0x0B43
#define HST_RFTC_MINHOPDUR                       0x0B44
#define HST_RFTC_MAXHOPDUR                       0x0B45
#define HST_RFTC_FRQHOPRANDSEED                  0x0B46
#define MAC_RFTC_FRQHOPSHFTREGVAL                0x0B47
#define MAC_RFTC_FRQHOPRANDNUMCNT                0x0B48
#define HST_RFTC_FRQCHINDEX                      0x0B49
#define HST_RFTC_PLLLOCKTIMEOUT                  0x0B4A
#define RESERVED_0x0B4B                          0x0B4B
#define RESERVED_0x0B4C                          0x0B4C
#define RESERVED_0x0B4D                          0x0B4D
#define HST_RFTC_BERREADDELAY                    0x0B4E
#define RESERVED_0x0B4F                          0x0B4F
#define MAC_RFTC_FWDRFPWRRAWADC                  0x0B50
#define MAC_RFTC_REVRFPWRRAWADC                  0x0B51
#define MAC_RFTC_ANTSENSERAWADC                  0x0B52
#define MAC_RFTC_AMBTEMPRAWADC                   0x0B53
#define MAC_RFTC_PATEMPRAWADC                    0x0B54
#define MAC_RFTC_XCVRTEMPRAWADC                  0x0B55
#define MAC_RFTC_PACURRENT                       0x0B56
#define MAC_RFTC_PACURRENTADC                    0x0B57
#define RESERVED_0x0B58                          0x0B58
#define RESERVED_0x0B59                          0x0B59
#define RESERVED_0x0B5A                          0x0B5A
#define RESERVED_0x0B5B                          0x0B5B
#define RESERVED_0x0B5C                          0x0B5C
#define RESERVED_0x0B5D                          0x0B5D
#define RESERVED_0x0B5E                          0x0B5E
#define HST_RFTC_ACTIVE_PROFILE                  0x0B5F
#define HST_RFTC_CURRENT_PROFILE                 0x0B60
#define HST_RFTC_PROF_SEL                        0x0B61
#define MAC_RFTC_PROF_CFG                        0x0B62
#define MAC_RFTC_PROF_ID_HIGH                    0x0B63
#define MAC_RFTC_PROF_ID_LOW                     0x0B64
#define MAC_RFTC_PROF_IDVER                      0x0B65
#define MAC_RFTC_PROF_PROTOCOL                   0x0B66
#define MAC_RFTC_PROF_R2TMODTYPE                 0x0B67
#define MAC_RFTC_PROF_TARI                       0x0B68
#define MAC_RFTC_PROF_X                          0x0B69
#define MAC_RFTC_PROF_PW                         0x0B6A
#define MAC_RFTC_PROF_RTCAL                      0x0B6B
#define MAC_RFTC_PROF_TRCAL                      0x0B6C
#define MAC_RFTC_PROF_DIVIDERATIO                0x0B6D
#define MAC_RFTC_PROF_MILLERNUM                  0x0B6E
#define MAC_RFTC_PROF_T2RLINKFREQ                0x0B6F
#define MAC_RFTC_PROF_VART2DELAY                 0x0B70
#define MAC_RFTC_PROF_RXDELAY                    0x0B71
#define MAC_RFTC_PROF_MINTOTT2DELAY              0x0B72
#define MAC_RFTC_PROF_TXPROPDELAY                0x0B73
#define MAC_RFTC_PROF_RSSIAVECFG                 0x0B74
#define MAC_RFTC_PROF_PREAMCMD                   0x0B75
#define MAC_RFTC_PROF_FSYNCCMD                   0x0B76
#define MAC_RFTC_PROF_T2WAITCMD                  0x0B77
#define RESERVED_0x0B78                          0x0B78
#define RESERVED_0x0B79                          0x0B79
#define RESERVED_0x0B7A                          0x0B7A
#define RESERVED_0x0B7B                          0x0B7B
#define RESERVED_0x0B7C                          0x0B7C
#define RESERVED_0x0B7D                          0x0B7D
#define RESERVED_0x0B7E                          0x0B7E
#define RESERVED_0x0B7F                          0x0B7F
#define HST_RFTC_CAL_RFREVPWR_A2                 0x0B80
#define HST_RFTC_CAL_RFREVPWR_A1                 0x0B81
#define HST_RFTC_CAL_RFREVPWR_A0                 0x0B82
#define HST_RFTC_CAL_AMBIENT_TEMP_A2             0x0B83
#define HST_RFTC_CAL_AMBIENT_TEMP_A1             0x0B84
#define HST_RFTC_CAL_AMBIENT_TEMP_A0             0x0B85
#define HST_RFTC_CAL_XCVR_TEMP_A2                0x0B86
#define HST_RFTC_CAL_XCVR_TEMP_A1                0x0B87
#define HST_RFTC_CAL_XCVR_TEMP_A0                0x0B88
#define HST_RFTC_CAL_ANT_SENSE_A2                0x0B89
#define HST_RFTC_CAL_ANT_SENSE_A1                0x0B8A
#define HST_RFTC_CAL_ANT_SENSE_A0                0x0B8B
#define HST_RFTC_SJC_EXTERNALLOTHRSH             0x0B8C
#define HST_RFTC_PA_CURRENT_TRIM                 0x0B8D
#define HST_RFTC_CAL_PA_TEMP_A2                  0x0B8E
#define HST_RFTC_CAL_PA_TEMP_A1                  0x0B8F
#define HST_RFTC_CAL_PA_TEMP_A0                  0x0B90
#define HST_RFTC_CAL_PA_CURRENT_A2               0x0B91
#define HST_RFTC_CAL_PA_CURRENT_A1               0x0B92
#define HST_RFTC_CAL_PA_CURRENT_A0               0x0B93
#define HST_RFTC_CAL_EPC_RSSI                    0x0B94
#define RESERVED_0x0C00                          0x0C00
#define HST_RFTC_FRQCH_SEL                       0x0C01
#define HST_RFTC_FRQCH_CFG                       0x0C02
#define HST_RFTC_FRQCH_DESC_PLLDIVMULT           0x0C03
#define HST_RFTC_FRQCH_DESC_PLLDACCTL            0x0C04
#define MAC_RFTC_FRQCH_DESC_PLLLOCKSTAT0         0x0C05
#define MAC_RFTC_FRQCH_DESC_PLLLOCKSTAT1         0x0C06
#define RESERVED_0x0C07                          0x0C07
#define HST_RFTC_FRQCH_CMDSTART                  0x0C08
#define HST_RFTC_PLL_LAST_LOCK_FREQ              0x0C09
#define RESERVED_CUSTOMER                        0x0F00
#define HST_CMD                                  0xF000

#define NUM_DEFINED_REGS                         276
#define NUM_RESERVED_REGS                        90
#define REG_WORD_COUNT                           1233

/* Block Constants */

#define REGBLOCK_00_LEN                          19
#define REGBLOCK_01_LEN                          41
#define REGBLOCK_02_LEN                          5
#define REGBLOCK_03_LEN                          15
#define REGBLOCK_04_LEN                          11
#define REGBLOCK_05_LEN                          6
#define REGBLOCK_06_LEN                          4
#define REGBLOCK_07_LEN                          8
#define REGBLOCK_08_LEN                          13
#define REGBLOCK_09_LEN                          57
#define REGBLOCK_0A_LEN                          26
#define REGBLOCK_0B_LEN                          149
#define REGBLOCK_0C_LEN                          10
#define REGBLOCK_0F_LEN                          1
#define REGBLOCK_F0_LEN                          1

#define NUM_REGBLOCKS                            15

#endif //H_HOSTIFREGS_H

/* End of generated file */

